### ISSUE TITLE
Social media icons should fade to white when it's being hovered

### ISSUE THREAD

**Issue by andrewhong04** [rutgersesports/rutgersesports.club#8]
The social media icons in question:
<img width="256" alt="image" src="https://user-images.githubusercontent.com/35881688/213029065-c0cfb21c-c0d8-4c5f-a22e-d77e5e3e4daa.png">

**Comment by BoltUltra** [comment]
I would like to work on it

**Comment by andrewhong04** [comment]
> I would like to work on it

Go ahead! :)
