### ISSUE TITLE
Scrollwheel should scroll club cards section

### ISSUE THREAD

**Issue by andrewhong04** [rutgersesports/rutgersesports.club#9]
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/35881688/213029428-96cf2f28-aa08-4672-8c52-93f016d09ec6.png">

**Comment by TinnyTin** [comment]
I can take a look at this if you don't mind~

**Comment by andrewhong04** [comment]
> I can take a look at this if you don't mind~

Go ahead!

**Comment by andrewhong04** [comment]
See #13 for more info
